version: "3.5"
services:
  digimondb:
    image: mysql:5.6
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - db-data-digimon:/var/lib/mysql
      - ./db/initialize:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 33061:3306
volumes:
  db-data-digimon:
